# UUID de um jogador Minecraft que servirá como "conta bancária do servidor".
# Pode ser trocado para qualquer UUID de jogador para servir de cofre/tesouraria.
ServerUUID: 5e8127e5-646b-36d6-9ff7-ace1050597d8
